### ISSUE TITLE
Integrate missing indices command for nextcloud

### ISSUE THREAD

**Issue by electricallen** [electricallen/homelab-ansible#1]
Currently, running the nextcloud `occ` command to fix missing indices is recommended to the user through README.md. Ideally, this would be accomplished as part of the ansible playbook. 

My first trhought is to do this 
```yaml
  - shell:
      cmd: docker-compose exec --user www-data nextcloud php occ db:add-missing-indices
      chdir: ~/nextcloud/
    register: nextcloud_indices
    changed_when: nextcloud_indices.rc != 0
```

Some quick testing shows return code 1 = failed, 0 = unchanged. Above code seems to work, will need to try passing in admin credentials to docker-compose to get setup completed prior to running this command
